#!/bin/env python

# NOTE: this script is slop and it's generated by LLM
#       but it WORKS.
# TODO: rewrite this entire shit

import json

def ternary_to_decimal(s):
    try:
        return int(s, 3)
    except ValueError:
        return 0

def get_unicode_glyph(cp_str):
    if not cp_str or cp_str == "U+????":
        return " "
    cp_val = int(cp_str.replace('U+', ''), 16)
    # Replicate validate.py control glyph logic
    if cp_val <= 0x20:
        return chr(0x2400 + cp_val)
    if cp_val == 0x7F:
        return chr(0x2421) # DEL
    return chr(cp_val)

def format_glyph(glyph, backticks=1, unmapped_label="*UNMAPPED*"):
    if glyph is None:
        return unmapped_label
    if glyph == "`":
        return "`` ` ``"
    if glyph == "|":
        return "`\\|`"
    if glyph == " ":
        if backticks == 1: return "` `"
        return "`␠`" # Special for unicode table space
    return f"`{glyph}`"

def align_table(rows, headers, aligns=None):
    if aligns is None:
        aligns = ["left"] * len(headers)

    all_data = [headers] + rows
    widths = [max(len(str(row[i])) for row in all_data) for i in range(len(headers))]

    output = []

    output.append(
        "| " + " | ".join(
            f"{headers[i]:<{widths[i]}}" for i in range(len(headers))
        ) + " |"
    )

    sep = []
    for w, a in zip(widths, aligns):
        if a == "center":
            sep.append(":" + "-" * w + ":")
        elif a == "right":
            sep.append("-" * (w+1) + ":")
        else:
            sep.append(":" + "-" * (w+1))

    output.append("|" + "|".join(sep) + "|")

    for row in rows:
        cells = []
        for i, cell in enumerate(row):
            cell = str(cell)

            if aligns[i] == "center":
                cells.append(cell.center(widths[i]))
            elif aligns[i] == "right":
                cells.append(cell.rjust(widths[i]))
            else:
                cells.append(cell.ljust(widths[i]))

        output.append("| " + " | ".join(cells) + " |")

    return "\n".join(output)

def generate():
    with open('spec.json', 'r', encoding='utf-8') as f:
        spec = json.load(f)

    chars = spec["characters"]
    categories = spec["categories"]

    # 1. Generate character-codes.md
    with open('src/character-codes.md', 'w', encoding='utf-8') as f:
        f.write("# Character Codes\n\n")
        f.write("This document defines the mapping between tryte values and characters in the Ternary Standard Character Set (TSCS).\n\n")
        f.write("> [!IMPORTANT]\n")
        f.write("> The specific mapping of numeric values to characters is currently a WIP.\n\n")

        f.write("## Overview\n\n")
        summary_headers = ["Ternary Range", "Decimal Range", "Category"]
        summary_rows = []
        for cat in categories:
            if cat["items"]:
                first_code = cat["items"][0]
                last_code = cat["items"][-1]
                first_dec = ternary_to_decimal(first_code)
                last_dec = ternary_to_decimal(last_code)
                summary_rows.append([
                    f"`{first_code}` .. `{last_code}`",
                    f"{first_dec} .. {last_dec}",
                    cat["name"]
                ])
        f.write(align_table(summary_rows, summary_headers) + "\n\n")
        
        for cat in categories:
            f.write(f"\n{'#' * cat['level']} {cat['name']}\n\n")
            if cat['description']:
                f.write(f"{cat['description']}\n\n")
            
            if cat['name'] == "Control Codes":
                headers = ["Code", "Decimal", "Mnemonic", "Name", "Description"]
                rows = []
                for code in cat["items"]:
                    c = chars[code]
                    rows.append([code, ternary_to_decimal(code), c.get("mnemonic", ""), c["name"], c.get("description", "")])
                f.write(align_table(rows, headers) + "\n")
                f.write("\n> [!NOTE]\n")
                f.write("> All codes from 000102 to 000222 are reserved for new control codes and other future extensions\n")
            elif cat["items"]:
                headers = ["Code", "Decimal", "Name"]
                rows = []
                for code in cat["items"]:
                    c = chars[code]
                    rows.append([code, ternary_to_decimal(code), c["name"]])
                f.write(align_table(rows, headers) + "\n")

    # 2. Generate ascii-mapping.md
    with open('src/ascii-mapping.md', 'w', encoding='utf-8') as f:
        f.write("# TSCS to ASCII Mapping\n\n")
        f.write("This page provides a direct translation mapping from the Ternary Standard Character Set (TSCS) to standard ASCII equivalents. \n")
        f.write("For TSCS characters that do not have a valid representation in 7-bit ASCII (such as extended symbols or mathematical characters)\n")
        f.write("the conversion is explicitly marked with *UNMAPPED*.\n")
        
        for cat in categories:
            if cat['level'] == 2 and cat['name'] == "Control Codes": continue # Not in original ascii-mapping.md
            
            # Reconstruct sections
            has_ascii = any("ascii" in chars[code] and chars[code]["ascii"] is not None for code in cat["items"])
            
            if cat['level'] >= 2:
                f.write(f"\n### {cat['name']}\n")
                if not has_ascii and cat["items"]:
                     f.write(f"None of TSCS {cat['name'].lower()} have ASCII equivalent.\n")
                elif cat["items"]:

                    headers = ["TSCS Code", "Decimal", "TSCS Name", "ASCII Glyph", "ASCII Hex"]
                    rows = []
                    for code in cat["items"]:
                        c = chars[code]
                        glyph = c.get("ascii")
                        rows.append([
                            code, 
                            ternary_to_decimal(code), 
                            c["name"], 
                            format_glyph(glyph), 
                            f"`0x{ord(glyph):02X}`" if glyph else "*NONE*"
                        ])
                    if rows:
                        f.write("\n" + align_table(rows, headers) + "\n")

    # 3. Generate unicode-mapping.md
    with open('src/unicode-mapping.md', 'w', encoding='utf-8') as f:
        f.write("# TSCS to Unicode Mapping\n")
        
        for cat in categories:
            if cat['level'] == 2 and cat['name'] == "Control Codes": continue
            
            if cat['level'] >= 2:
                f.write(f"\n### {cat['name']}\n\n")
                if cat["items"]:
                    headers = ["Code", "Decimal", "Name", "Unicode Code Point", "Glyph"]
                    rows = []
                    for code in cat["items"]:
                        c = chars[code]
                        u_cp = c.get("unicode", "U+????")
                        glyph = get_unicode_glyph(u_cp)
                        rows.append([
                            code,
                            ternary_to_decimal(code),
                            c["name"],
                            f"`{u_cp}`",
                            format_glyph(glyph, backticks=2)
                        ])
                    f.write(
                        align_table(
                            rows,
                            headers,
                            ["left", "left", "left", "left", "center"]
                        ) + "\n"
                    )

if __name__ == "__main__":
    generate()

