#!/bin/env python

# NOTE: this script is slop and it's generated by LLM
#       but it WORKS. i just needed simple script to prevent
#       common mistakes

import sys
import os

def ternary_to_decimal(s):
    try:
        return int(s, 3)
    except ValueError:
        return -1

def get_control_glyph(code_point):
    # Mapping for Unicode Control Pictures (U+2400 block)
    if code_point <= 0x20:
        return chr(0x2400 + code_point)
    if code_point == 0x7F:
        return chr(0x2421) # DEL
    return None

def parse_markdown_row(line):
    # Handle escaped pipes \| by temporarily replacing them
    line = line.replace(r'\|', '___ESCAPED_PIPE___')
    parts = [p.strip() for p in line.split('|')]
    # Restore escaped pipes in each part
    parts = [p.replace('___ESCAPED_PIPE___', '|') for p in parts]
    return parts

def extract_glyph(raw_glyph):
    # Glyphs are often wrapped in backticks: `a` or `` ` ``
    # We want to extract the content.
    s = raw_glyph.strip()
    if s.startswith('``') and s.endswith('``'):
        return s[2:-2].strip() or ' ' # Double backticks often used for single backtick or space
    if s.startswith('`') and s.endswith('`'):
        content = s[1:-1]
        return content
    return s

def validate_character_codes(file_path):
    print(f"Validating {file_path}...")
    errors = []
    data = {} # tscs_code -> {decimal, name}
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    used_decimals = {}

    for i, line in enumerate(lines):
        line = line.strip()
        if not line.startswith('|') or 'Code' in line or ':---' in line:
            continue
        
        parts = parse_markdown_row(line)
        if len(parts) < 4:
            continue
            
        tscs_code = parts[1]
        decimal_val_str = parts[2]
        
        # In character-codes.md:
        # Control: | Code | Decimal | Mnemonic | Name | Description | (len 6)
        # Graphic: | Code | Decimal | Name | (len 4)
        if len(parts) >= 6:
            name = parts[4]
        else:
            name = parts[3]

        try:
            decimal_val = int(decimal_val_str)
            expected_decimal = ternary_to_decimal(tscs_code)
            if expected_decimal != decimal_val:
                errors.append(f"Line {i+1}: TSCS Code {tscs_code} (ternary) should be {expected_decimal}, but found {decimal_val}")
            
            if tscs_code in data:
                errors.append(f"Line {i+1}: Duplicate TSCS Code {tscs_code}")
            if decimal_val in used_decimals:
                errors.append(f"Line {i+1}: Duplicate Decimal value {decimal_val} (previously at line {used_decimals[decimal_val]})")
            
            used_decimals[decimal_val] = i + 1
            data[tscs_code] = {'decimal': decimal_val, 'name': name}

        except ValueError:
             errors.append(f"Line {i+1}: Invalid TSCS Code or Decimal format: {tscs_code}, {decimal_val_str}")
             continue
    
    return errors, data

def validate_ascii_mapping(file_path):
    print(f"Validating {file_path}...")
    errors = []
    data = {} # tscs_code -> {decimal, name, glyph, hex}
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    used_decimals = {}

    for i, line in enumerate(lines):
        line = line.strip()
        if not line.startswith('|') or 'TSCS Code' in line or ':---' in line:
            continue
        
        parts = parse_markdown_row(line)
        if len(parts) < 6:
            continue
        
        tscs_code = parts[1]
        decimal_val_str = parts[2]
        name = parts[3]
        ascii_glyph = extract_glyph(parts[4])
        ascii_hex = parts[5].replace('`', '').strip()
        
        # 1. Ternary to Decimal
        try:
            decimal_val = int(decimal_val_str)
            expected_decimal = ternary_to_decimal(tscs_code)
            if expected_decimal != decimal_val:
                errors.append(f"Line {i+1}: TSCS Code {tscs_code} (ternary) should be {expected_decimal}, but found {decimal_val}")
            
            if tscs_code in data:
                errors.append(f"Line {i+1}: Duplicate TSCS Code {tscs_code}")
            if decimal_val in used_decimals:
                errors.append(f"Line {i+1}: Duplicate Decimal value {decimal_val} (previously at line {used_decimals[decimal_val]})")
            
            used_decimals[decimal_val] = i + 1
            data[tscs_code] = {'decimal': decimal_val, 'name': name, 'glyph': ascii_glyph, 'hex': ascii_hex}

        except ValueError:
            errors.append(f"Line {i+1}: Invalid TSCS Code or Decimal format: {tscs_code}, {decimal_val_str}")
            continue

        # 2. ASCII Hex to Glyph
        if ascii_glyph != "*UNMAPPED*" and ascii_hex != "*NONE*":
            try:
                hex_val = int(ascii_hex, 16)
                expected_glyph = chr(hex_val)
                
                actual_glyph = ascii_glyph
                if expected_glyph != actual_glyph:
                    errors.append(f"Line {i+1}: ASCII Hex {ascii_hex} ({expected_glyph}) does not match glyph '{actual_glyph}'")
            except ValueError:
                errors.append(f"Line {i+1}: Invalid ASCII Hex format: {ascii_hex}")
                
    return errors, data

def validate_unicode_mapping(file_path):
    print(f"Validating {file_path}...")
    errors = []
    data = {} # tscs_code -> {decimal, name, glyph, cp}
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    used_decimals = {}

    for i, line in enumerate(lines):
        line = line.strip()
        if not line.startswith('|') or 'Code' in line or ':---' in line:
            continue
        
        parts = parse_markdown_row(line)
        if len(parts) < 6:
            continue
            
        tscs_code = parts[1]
        decimal_val_str = parts[2]
        name = parts[3]
        
        u_code_point = None
        glyph = None
        
        # Try to find U+ and then next part is glyph
        for j, p in enumerate(parts):
            if 'U+' in p:
                u_code_point = p.replace('`', '').strip()
                if j + 1 < len(parts):
                    glyph = extract_glyph(parts[j+1])
                break
        
        if not u_code_point:
            continue

        # 1. Ternary to Decimal
        try:
            decimal_val = int(decimal_val_str)
            expected_decimal = ternary_to_decimal(tscs_code)
            if expected_decimal != decimal_val:
                errors.append(f"Line {i+1}: TSCS Code {tscs_code} (ternary) should be {expected_decimal}, but found {decimal_val}")
            
            if tscs_code in data:
                errors.append(f"Line {i+1}: Duplicate TSCS Code {tscs_code}")
            if decimal_val in used_decimals:
                errors.append(f"Line {i+1}: Duplicate Decimal value {decimal_val} (previously at line {used_decimals[decimal_val]})")
            
            used_decimals[decimal_val] = i + 1
            data[tscs_code] = {'decimal': decimal_val, 'name': name, 'glyph': glyph, 'cp': u_code_point}

        except ValueError:
             errors.append(f"Line {i+1}: Invalid TSCS Code or Decimal format: {tscs_code}, {decimal_val_str}")
             continue

        # 2. Unicode Code Point to Glyph
        if u_code_point != "U+????":
            try:
                cp_val = int(u_code_point.replace('U+', ''), 16)
                expected_char = chr(cp_val)
                actual_glyph = glyph
                
                control_glyph = get_control_glyph(cp_val)
                if control_glyph:
                    if actual_glyph != control_glyph:
                        errors.append(f"Line {i+1}: Unicode {u_code_point} should use control glyph '{control_glyph}', but found '{actual_glyph}'")
                else:
                    if expected_char != actual_glyph:
                        errors.append(f"Line {i+1}: Unicode {u_code_point} ({expected_char}) does not match glyph '{actual_glyph}'")
                        
            except ValueError:
                errors.append(f"Line {i+1}: Invalid Unicode Code Point format: {u_code_point}")

    return errors, data

def main():
    char_file = 'src/character-codes.md'
    ascii_file = 'src/ascii-mapping.md'
    unicode_file = 'src/unicode-mapping.md'
    
    all_errors = []
    
    char_data = {}
    ascii_data = {}
    unicode_data = {}

    if os.path.exists(char_file):
        errs, char_data = validate_character_codes(char_file)
        all_errors.extend(errs)

    if os.path.exists(ascii_file):
        errs, ascii_data = validate_ascii_mapping(ascii_file)
        all_errors.extend(errs)
        
    if os.path.exists(unicode_file):
        errs, unicode_data = validate_unicode_mapping(unicode_file)
        all_errors.extend(errs)

    # Cross-file consistency
    print("Checking cross-file consistency...")
    
    # Check ASCII against Character Codes
    for code, info in ascii_data.items():
        if code in char_data:
            if info['decimal'] != char_data[code]['decimal']:
                all_errors.append(f"Consistency Error: Decimal for {code} is {info['decimal']} in ASCII but {char_data[code]['decimal']} in Char Codes")
            if info['name'] != char_data[code]['name']:
                all_errors.append(f"Consistency Error: Name for {code} is '{info['name']}' in ASCII but '{char_data[code]['name']}' in Char Codes")
        else:
             all_errors.append(f"Consistency Error: TSCS Code {code} found in ASCII mapping but not in character-codes.md")

    # Check Unicode against Character Codes
    for code, info in unicode_data.items():
        if code in char_data:
            if info['decimal'] != char_data[code]['decimal']:
                all_errors.append(f"Consistency Error: Decimal for {code} is {info['decimal']} in Unicode but {char_data[code]['decimal']} in Char Codes")
            # Note: Unicode mapping names might have slight variations (case, etc) but let's check
            if info['name'].lower() != char_data[code]['name'].lower():
                all_errors.append(f"Consistency Error: Name for {code} is '{info['name']}' in Unicode but '{char_data[code]['name']}' in Char Codes")
        else:
             all_errors.append(f"Consistency Error: TSCS Code {code} found in Unicode mapping but not in character-codes.md")

    if all_errors:
        print("\nValidation FAILED:")
        for err in all_errors:
            print(f"  - {err}")
        sys.exit(1)
    else:
        print("\nValidation PASSED!")
        sys.exit(0)

if __name__ == "__main__":
    main()
