#!/bin/env python

# NOTE: this script is slop and it's generated by LLM
#       but it WORKS. i just needed simple script to prevent
#       common mistakes

import sys
import os

def ternary_to_decimal(s):
    return int(s, 3)

def get_control_glyph(code_point):
    # Mapping for Unicode Control Pictures (U+2400 block)
    if code_point <= 0x20:
        return chr(0x2400 + code_point)
    if code_point == 0x7F:
        return chr(0x2421) # DEL
    return None

def parse_markdown_row(line):
    # Handle escaped pipes \| by temporarily replacing them
    line = line.replace(r'\|', '___ESCAPED_PIPE___')
    parts = [p.strip() for p in line.split('|')]
    # Restore escaped pipes in each part
    parts = [p.replace('___ESCAPED_PIPE___', '|') for p in parts]
    return parts

def extract_glyph(raw_glyph):
    # Glyphs are often wrapped in backticks: `a` or `` ` ``
    # We want to extract the content.
    s = raw_glyph.strip()
    if s.startswith('``') and s.endswith('``'):
        return s[2:-2].strip() or ' ' # Double backticks often used for single backtick or space
    if s.startswith('`') and s.endswith('`'):
        content = s[1:-1]
        # Special case: if content is empty, it was `` ` `` which became ` ` after strip or something?
        # Actually ` ` is space.
        return content
    return s

def validate_ascii_mapping(file_path):
    print(f"Validating {file_path}...")
    errors = []
    data = {} # tscs_code -> {decimal, glyph, hex}
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    used_decimals = {}

    for i, line in enumerate(lines):
        line = line.strip()
        if not line.startswith('|') or 'TSCS Code' in line or ':---' in line:
            continue
        
        parts = parse_markdown_row(line)
        if len(parts) < 6:
            continue
        
        tscs_code = parts[1]
        decimal_val_str = parts[2]
        ascii_glyph = extract_glyph(parts[4])
        ascii_hex = parts[5].replace('`', '').strip()
        
        # 1. Ternary to Decimal
        try:
            decimal_val = int(decimal_val_str)
            expected_decimal = ternary_to_decimal(tscs_code)
            if expected_decimal != decimal_val:
                errors.append(f"Line {i+1}: TSCS Code {tscs_code} (ternary) should be {expected_decimal}, but found {decimal_val}")
            
            if tscs_code in data:
                errors.append(f"Line {i+1}: Duplicate TSCS Code {tscs_code}")
            if decimal_val in used_decimals:
                errors.append(f"Line {i+1}: Duplicate Decimal value {decimal_val} (previously at line {used_decimals[decimal_val]})")
            
            used_decimals[decimal_val] = i + 1
            data[tscs_code] = {'decimal': decimal_val, 'glyph': ascii_glyph, 'hex': ascii_hex}

        except ValueError:
            errors.append(f"Line {i+1}: Invalid TSCS Code or Decimal format: {tscs_code}, {decimal_val_str}")
            continue

        # 2. ASCII Hex to Glyph
        if ascii_glyph != "*UNMAPPED*" and ascii_hex != "*NONE*":
            try:
                hex_val = int(ascii_hex, 16)
                expected_glyph = chr(hex_val)
                
                actual_glyph = ascii_glyph
                if expected_glyph != actual_glyph:
                    errors.append(f"Line {i+1}: ASCII Hex {ascii_hex} ({expected_glyph}) does not match glyph '{actual_glyph}'")
            except ValueError:
                errors.append(f"Line {i+1}: Invalid ASCII Hex format: {ascii_hex}")
                
    return errors, data

def validate_unicode_mapping(file_path):
    print(f"Validating {file_path}...")
    errors = []
    data = {} # tscs_code -> {decimal, glyph, cp}
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    used_decimals = {}

    for i, line in enumerate(lines):
        line = line.strip()
        if not line.startswith('|') or 'Code' in line or ':---' in line:
            continue
        
        parts = parse_markdown_row(line)
        if len(parts) < 6:
            continue
            
        tscs_code = parts[1]
        decimal_val_str = parts[2]
        
        u_code_point = None
        glyph = None
        
        for p in parts:
            if 'U+' in p:
                u_code_point = p.replace('`', '').strip()
            elif u_code_point and glyph is None:
                glyph = extract_glyph(p)
        
        if not u_code_point:
            continue

        # 1. Ternary to Decimal
        try:
            decimal_val = int(decimal_val_str)
            expected_decimal = ternary_to_decimal(tscs_code)
            if expected_decimal != decimal_val:
                errors.append(f"Line {i+1}: TSCS Code {tscs_code} (ternary) should be {expected_decimal}, but found {decimal_val}")
            
            if tscs_code in data:
                errors.append(f"Line {i+1}: Duplicate TSCS Code {tscs_code}")
            if decimal_val in used_decimals:
                errors.append(f"Line {i+1}: Duplicate Decimal value {decimal_val} (previously at line {used_decimals[decimal_val]})")
            
            used_decimals[decimal_val] = i + 1
            data[tscs_code] = {'decimal': decimal_val, 'glyph': glyph, 'cp': u_code_point}

        except ValueError:
             errors.append(f"Line {i+1}: Invalid TSCS Code or Decimal format: {tscs_code}, {decimal_val_str}")
             continue

        # 2. Unicode Code Point to Glyph
        try:
            cp_val = int(u_code_point.replace('U+', ''), 16)
            expected_char = chr(cp_val)
            actual_glyph = glyph
            
            control_glyph = get_control_glyph(cp_val)
            if control_glyph:
                if actual_glyph != control_glyph:
                    errors.append(f"Line {i+1}: Unicode {u_code_point} should use control glyph '{control_glyph}', but found '{actual_glyph}'")
            else:
                if expected_char != actual_glyph:
                    errors.append(f"Line {i+1}: Unicode {u_code_point} ({expected_char}) does not match glyph '{actual_glyph}'")
                    
        except ValueError:
            errors.append(f"Line {i+1}: Invalid Unicode Code Point format: {u_code_point}")

    return errors, data

def main():
    ascii_file = 'src/ascii-mapping.md'
    unicode_file = 'src/unicode-mapping.md'
    
    all_errors = []
    
    ascii_data = {}
    unicode_data = {}

    if os.path.exists(ascii_file):
        errs, ascii_data = validate_ascii_mapping(ascii_file)
        all_errors.extend(errs)
        
    if os.path.exists(unicode_file):
        errs, unicode_data = validate_unicode_mapping(unicode_file)
        all_errors.extend(errs)

    # Cross-file consistency
    print("Checking cross-file consistency...")
    for tscs_code in ascii_data:
        if tscs_code in unicode_data:
            a_glyph = ascii_data[tscs_code]['glyph']
            u_glyph = unicode_data[tscs_code]['glyph']
            
            if a_glyph != "*UNMAPPED*":
                # For some characters, Unicode uses control symbols but ASCII uses the actual char or name
                # Actually for graphic characters they should match.
                # For control characters, ASCII mapping might have something else?
                # Let's check a few.
                # Space: ASCII ` `, Unicode `␠`
                # We need to normalize these for comparison.
                
                # Check if it's a control character (decimal < 33 or 127)
                decimal = ascii_data[tscs_code]['decimal']
                if decimal < 33 or decimal == 127 or decimal == 89: # 89 is Space
                    # Control characters - we expect them to be different glyphs in these docs
                    # as Unicode mapping uses Control Pictures.
                    pass
                else:
                    if a_glyph != u_glyph:
                        all_errors.append(f"Consistency Error: TSCS Code {tscs_code} is '{a_glyph}' in ASCII but '{u_glyph}' in Unicode")

    if all_errors:
        print("\nValidation FAILED:")
        for err in all_errors:
            print(f"  - {err}")
        sys.exit(1)
    else:
        print("\nValidation PASSED!")
        sys.exit(0)

if __name__ == "__main__":
    main()
